Creating react app
dancecoder/chain-book pull request #4
Opened 2021-10-01 13:01 UTC by sanchine

создание react веб-приложения

2021-10-06 15:41 UTC, dancecoder requested changes

2021-10-06 15:41 UTC, dancecoder commented on frontend/chain-book/public/rm.txt
> +folder for public
файл должен называться README.md 

.md - расширение для файлов  с разметкой MarkDown

README.md  - волшебное имя файла, содержимое этих файлов отображается под списком файлов в каждой папке на github

2021-10-06 15:41 UTC, dancecoder commented on frontend/chain-book/src/App.js
> +export default App;
export default - это дурной тон. Нужно исправить на обычный экспорт. Соответственно придется изменить импорт.

2021-10-06 15:41 UTC, dancecoder commented on frontend/chain-book/src/rm.txt
> +папка с ресурсами src
README.md

2021-10-06 15:41 UTC, dancecoder commented on frontend/chain-book/src/index.js
> +reportWebVitals();
web-vitals надо выкосить, есть риск впасть с ним в преждевременную оптимизацию

2021-10-12 13:06 UTC, dancecoder approved these changes

2021-10-14 15:03 UTC, sanchine commented
Создание React.js приложения

2021-10-14 15:04 UTC, merged